### ISSUE TITLE
UUID generator - server 

### ISSUE THREAD

**Issue by didhat** [didhat/Messenger_HSE_lab#1]
Мне лень тут на английском писать.
Вообщем нужно сделать модуль на сервере(название сами выбрите), который будет просто генерировать код по стандарту uuid. Можете писать сами или взять встроеннуюб но она вроде только для cpp, а у нас хардкор вбщт. 
Вот значит требования;
- отедльный модуль в папке(Server);
- принимает указатель на char*
- ничего не возврощает, но в указателеб который передавался лежит uuid code, на его конце естественно '\0'
- интегрировать это в проект в Server/RequestHandler/RequestHandler.c , в этом в файле в функции Login генерится код, добавляется в ответ клиенту, а также code_list_globalConfigs.

**Comment by Allokanic** [comment]
done
