### ISSUE TITLE
Фикс бага, свзанный с базой данных

### ISSUE THREAD

**Issue by didhat** [didhat/Messenger_HSE_lab#7]
Когда мы записываем в базу данных что-то строковое, то синтаксис выглядит так: string = 'something'. Это something вводит пользователь и если в строке будет ' вот это, то мы получим баг. Необходимо написать обработчик строки, который будет это исправлять. То есть модифицировать строку, чтобы сделать корректный запрос. Там вроде перед ' надо добавить \ 
Примерно что-то такое. На сервере можно добавить этот модуль в HelpScripts, например.

**Comment by YawKar** [comment]
Готово
